version: "3.3"

services:
  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db_rest
    volumes:
    - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
