version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db_rest
    volumes:
    - mysql-data:/var/lib/mysql
  api:
    image: n1c0l4stournier/springboot.rest:1.0.0
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASS: pass
    deploy:
      replicas: 2
    ports:
    - 8181:8181
volumes:
  mysql-data:
