apiVersion: v1
kind: Service
metadata:
  name: {{ template "app-chart.fullname" . }}
  labels:
    app: {{ template "app-chart.name" . }}
    chart: {{ template "app-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ template "app-chart.fullname" . }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ template "app-chart.name" . }}
    release: {{ .Release.Name }}