spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}/${DB_NAME:db_rest}
    username: ${DB_USER:debian-sys-maint}
    password: ${DB_PASS:3Xf6hcpbyySgX9Tu}
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8181
