apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-rest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-rest
    spec:
      containers:
      - image: n1c0l4stournier/springboot.rest:0.0.2
        name: springboot-rest
        env:
        - name: DB_USER
          value: root
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-root-password
        - name: DB_HOST
          value: mysql-service
        - name: DB_PORT
          value: "3306"