apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: n1c0l4stournier/springboot.rest:latest
        imagePullPolicy: Always
        name: springboot-rest
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mysql-database
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mysql-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-password
        - name: DB_URL
          value: mysql-service